# Import Modules

In [102]:
import pandas as pd
import numpy as np

# Read CSV

In [103]:
pd.set_option("display.max_columns", 40)

In [104]:
df = pd.read_csv("../csv_files/hr_job_placement_dataset_cleaned.csv")

In [105]:
df.head()

,age_years,gender,ssc_percentage,hsc_percentage,degree_percentage,degree_specialization,technical_score,aptitude_score,communication_score,skills_match_percentage,certifications_count,internship_experience,years_of_experience,career_switch_willingness,relevant_experience,previous_ctc_lpa,expected_ctc_lpa,company_tier,job_role_match,competition_level,bond_requirement,notice_period_days,layoff_history,employment_gap_months,relocation_willingness,status
0,27,Male,65.062,83.843,75.857,Computer Science,58.222,89.566,64.474,79.549,2,No,1,Willing,Relevant,3.531,5.806,Tier 3,Not Matched,Medium,Not Required,15,No,18,Not Willing,Not Placed
1,24,Male,67.886,64.973,73.094,Electronics,71.928,54.592,61.077,73.316,1,Yes,0,Not Willing,Relevant,9.858,10.808,Tier 1,Matched,High,Required,0,No,3,Not Willing,Not Placed
2,33,Female,73.892,68.834,90.196,Information Technology,72.445,58.587,79.495,75.467,1,Yes,1,Willing,Relevant,5.802,5.477,Tier 3,Not Matched,Low,Not Required,0,No,3,Not Willing,Placed
3,31,Male,74.146,76.255,75.587,Mechanical,78.856,61.022,53.740,73.676,2,No,0,Not Willing,Relevant,2.130,9.981,Tier 2,Matched,Low,Not Required,0,Yes,6,Willing,Not Placed
4,28,Male,60.476,65.786,80.801,Information Technology,68.287,65.714,61.438,88.995,1,No,0,Willing,Not Relevant,7.948,8.921,Tier 2,Matched,Medium,Not Required,0,No,3,Willing,Not Placed

# Feature Engineering

In [106]:
df.columns

Index(['age_years', 'gender', 'ssc_percentage', 'hsc_percentage',
       'degree_percentage', 'degree_specialization', 'technical_score',
       'aptitude_score', 'communication_score', 'skills_match_percentage',
       'certifications_count', 'internship_experience', 'years_of_experience',
       'career_switch_willingness', 'relevant_experience', 'previous_ctc_lpa',
       'expected_ctc_lpa', 'company_tier', 'job_role_match',
       'competition_level', 'bond_requirement', 'notice_period_days',
       'layoff_history', 'employment_gap_months', 'relocation_willingness',
       'status'],
      dtype='str')

## Experience category (Fresher / Junior / Senior)

In [107]:
df["years_of_experience"].value_counts()

years_of_experience
0    14952
1    13508
2     9966
3     6538
4     3548
5     1488
Name: count, dtype: int64

In [108]:
df["exp_category"] = df["years_of_experience"].apply(
    lambda x: 
    "Fresher" if x == 0 else 
    "Junior" if x in [1, 2] 
    else "Senior"
)

In [109]:
df["exp_category"].value_counts()

exp_category
Junior     23474
Fresher    14952
Senior     11574
Name: count, dtype: int64

---

## Academic performance bands
- 0-50   : Poor 
- 50-70  : Average  
- 70-85  : Good 
- 85-100 : Excellent

In [110]:
df["academic_score"] = round(df[['ssc_percentage', 'hsc_percentage', 'degree_percentage']].mean(axis=1), 3)

In [111]:
df["academic_perfomance"] = df["academic_score"].apply(
    lambda x:
    "Poor" if 0 <= x < 50
    else "Average" if 50 <= x < 70
    else "Good" if 70 <= x <= 85
    else "Excellent"
)

---

## Skills match level (Low / Medium / High)

In [112]:
df.head()

,age_years,gender,ssc_percentage,hsc_percentage,degree_percentage,degree_specialization,technical_score,aptitude_score,communication_score,skills_match_percentage,certifications_count,internship_experience,years_of_experience,career_switch_willingness,relevant_experience,previous_ctc_lpa,expected_ctc_lpa,company_tier,job_role_match,competition_level,bond_requirement,notice_period_days,layoff_history,employment_gap_months,relocation_willingness,status,exp_category,academic_score,academic_perfomance
0,27,Male,65.062,83.843,75.857,Computer Science,58.222,89.566,64.474,79.549,2,No,1,Willing,Relevant,3.531,5.806,Tier 3,Not Matched,Medium,Not Required,15,No,18,Not Willing,Not Placed,Junior,74.921,Good
1,24,Male,67.886,64.973,73.094,Electronics,71.928,54.592,61.077,73.316,1,Yes,0,Not Willing,Relevant,9.858,10.808,Tier 1,Matched,High,Required,0,No,3,Not Willing,Not Placed,Fresher,68.651,Average
2,33,Female,73.892,68.834,90.196,Information Technology,72.445,58.587,79.495,75.467,1,Yes,1,Willing,Relevant,5.802,5.477,Tier 3,Not Matched,Low,Not Required,0,No,3,Not Willing,Placed,Junior,77.641,Good
3,31,Male,74.146,76.255,75.587,Mechanical,78.856,61.022,53.740,73.676,2,No,0,Not Willing,Relevant,2.130,9.981,Tier 2,Matched,Low,Not Required,0,Yes,6,Willing,Not Placed,Fresher,75.329,Good
4,28,Male,60.476,65.786,80.801,Information Technology,68.287,65.714,61.438,88.995,1,No,0,Willing,Not Relevant,7.948,8.921,Tier 2,Matched,Medium,Not Required,0,No,3,Willing,Not Placed,Fresher,69.021,Average

In [113]:
df["skill_level"] = df["skills_match_percentage"].apply(
    lambda x: 
    "Low" if 0 <= x < 50
    else "Medium" if 50 <= x < 75
    else "High"
)

---

## Interview performance category

In [114]:
df["interview_score"] = round(df[['technical_score', 'aptitude_score', 'communication_score']].mean(axis=1), 3)

In [115]:
df["interview_performance"] = df["interview_score"].apply(
    lambda x:
    "Poor" if x < 50
    else "Average" if x < 65
    else "Good" if x < 80
    else "Excellent"
)

In [116]:
df.head()

,age_years,gender,ssc_percentage,hsc_percentage,degree_percentage,degree_specialization,technical_score,aptitude_score,communication_score,skills_match_percentage,certifications_count,internship_experience,years_of_experience,career_switch_willingness,relevant_experience,previous_ctc_lpa,expected_ctc_lpa,company_tier,job_role_match,competition_level,bond_requirement,notice_period_days,layoff_history,employment_gap_months,relocation_willingness,status,exp_category,academic_score,academic_perfomance,skill_level,interview_score,interview_performance
0,27,Male,65.062,83.843,75.857,Computer Science,58.222,89.566,64.474,79.549,2,No,1,Willing,Relevant,3.531,5.806,Tier 3,Not Matched,Medium,Not Required,15,No,18,Not Willing,Not Placed,Junior,74.921,Good,High,70.754,Good
1,24,Male,67.886,64.973,73.094,Electronics,71.928,54.592,61.077,73.316,1,Yes,0,Not Willing,Relevant,9.858,10.808,Tier 1,Matched,High,Required,0,No,3,Not Willing,Not Placed,Fresher,68.651,Average,Medium,62.532,Average
2,33,Female,73.892,68.834,90.196,Information Technology,72.445,58.587,79.495,75.467,1,Yes,1,Willing,Relevant,5.802,5.477,Tier 3,Not Matched,Low,Not Required,0,No,3,Not Willing,Placed,Junior,77.641,Good,High,70.176,Good
3,31,Male,74.146,76.255,75.587,Mechanical,78.856,61.022,53.740,73.676,2,No,0,Not Willing,Relevant,2.130,9.981,Tier 2,Matched,Low,Not Required,0,Yes,6,Willing,Not Placed,Fresher,75.329,Good,Medium,64.539,Average
4,28,Male,60.476,65.786,80.801,Information Technology,68.287,65.714,61.438,88.995,1,No,0,Willing,Not Relevant,7.948,8.921,Tier 2,Matched,Medium,Not Required,0,No,3,Willing,Not Placed,Fresher,69.021,Average,High,65.146,Good

# Export CSV

In [117]:
df.isnull().sum()

age_years                    0
gender                       0
ssc_percentage               0
hsc_percentage               0
degree_percentage            0
degree_specialization        0
technical_score              0
aptitude_score               0
communication_score          0
skills_match_percentage      0
certifications_count         0
internship_experience        0
years_of_experience          0
career_switch_willingness    0
relevant_experience          0
previous_ctc_lpa             0
expected_ctc_lpa             0
company_tier                 0
job_role_match               0
competition_level            0
bond_requirement             0
notice_period_days           0
layoff_history               0
employment_gap_months        0
relocation_willingness       0
status                       0
exp_category                 0
academic_score               0
academic_perfomance          0
skill_level                  0
interview_score              0
interview_performance        0
dtype: int64

In [118]:
df.head()

,age_years,gender,ssc_percentage,hsc_percentage,degree_percentage,degree_specialization,technical_score,aptitude_score,communication_score,skills_match_percentage,certifications_count,internship_experience,years_of_experience,career_switch_willingness,relevant_experience,previous_ctc_lpa,expected_ctc_lpa,company_tier,job_role_match,competition_level,bond_requirement,notice_period_days,layoff_history,employment_gap_months,relocation_willingness,status,exp_category,academic_score,academic_perfomance,skill_level,interview_score,interview_performance
0,27,Male,65.062,83.843,75.857,Computer Science,58.222,89.566,64.474,79.549,2,No,1,Willing,Relevant,3.531,5.806,Tier 3,Not Matched,Medium,Not Required,15,No,18,Not Willing,Not Placed,Junior,74.921,Good,High,70.754,Good
1,24,Male,67.886,64.973,73.094,Electronics,71.928,54.592,61.077,73.316,1,Yes,0,Not Willing,Relevant,9.858,10.808,Tier 1,Matched,High,Required,0,No,3,Not Willing,Not Placed,Fresher,68.651,Average,Medium,62.532,Average
2,33,Female,73.892,68.834,90.196,Information Technology,72.445,58.587,79.495,75.467,1,Yes,1,Willing,Relevant,5.802,5.477,Tier 3,Not Matched,Low,Not Required,0,No,3,Not Willing,Placed,Junior,77.641,Good,High,70.176,Good
3,31,Male,74.146,76.255,75.587,Mechanical,78.856,61.022,53.740,73.676,2,No,0,Not Willing,Relevant,2.130,9.981,Tier 2,Matched,Low,Not Required,0,Yes,6,Willing,Not Placed,Fresher,75.329,Good,Medium,64.539,Average
4,28,Male,60.476,65.786,80.801,Information Technology,68.287,65.714,61.438,88.995,1,No,0,Willing,Not Relevant,7.948,8.921,Tier 2,Matched,Medium,Not Required,0,No,3,Willing,Not Placed,Fresher,69.021,Average,High,65.146,Good

In [119]:
df.shape

(50000, 32)

In [120]:
df.to_csv("../csv_files/hr_job_placement_dataset_feature.csv")